### PR TITLE
[Bugfix]Fix VideoCaptureElement is black out when front buffer is unavailable.

### PR DESCRIPTION
**Pull request by Rhuaer**
See #61, #42 and #3

### CODE REVIEW

**Comment by xmedeko** [comment]
Looks good, I'll test that later. Just the user associated with the commits does not match your GitHub account.

**Comment by Rhuaer** [comment]
Yeah，the user is uesed for GitLab.
I deployed the same ssh key in github and gitlab

**Comment by xmedeko** [comment]
You may rewrite the commits, and `push --force` them, if you like.

**Comment by Rhuaer** [comment]
Done

**Comment by xmedeko** [comment]
@Rhuaer I'm sorry I've deleted your commits from your fork by a mistake. I still cannot do properly amending PR commits and merge them. But I will commit everything into the Sascha-L/WPF-MediaKit master soon, so you can check it again.
I've just fixed the TestApplication camera and media element switching.

**Comment by xmedeko** [comment]
@Rhuaer I'm sorry I've deleted your commits from your fork by a mistake. I still cannot do properly amending PR commits and merge them. But I will commit everything into the Sascha-L/WPF-MediaKit master soon, so you can check it again.
I've just fixed the TestApplication camera and media element switching.

**Pull request closed without merging**
