### PR TITLE
Adding IVideoFrameStep to player and VideoFrameRate to detector

### PR DESCRIPTION
**Pull request by skaterlui**
Adding IVideoFrameStep to Mediakit, to skip framecount forward when source is set.
Video can be skipped frame by frame.
Adding Videoframerate to mediadetector to get the current loaded media framerate (before playing).
Updating SampleApp with a framestep button and speedratio slider.

### CODE REVIEW

**Comment by xmedeko** [comment]
Please squash to one commit and rebase to the current master.
Also, the mouse wheel is not needed for the TestApplication. Catching the `PreviewMouseWheel` may clash with scrollbars (if someone adds them in the future.) The `TestApplication` is just a basic test, does not need to be cool.

**Comment by skaterlui** [comment]
@xmedeko 
I'm new to git. Using svn all the time. I'm not so familiar with the functions there. I was investigating a couple of hours how to squash my commits, with no success. Maybe you have a quick link with a tutorial for this task. If not, I'll get it working over time...

**Comment by Rhuaer** [comment]
@skaterlui  You can google 'git rebase interactive' or see this [post](https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history)

**Comment by xmedeko** [comment]
@skaterlui If you do not know how to squash the commits, then some solutions are:
1. I can squash your commits to your repo, but it would rewrite your repo `skaterlui:master`. (When you open a PR you grant a limited access to your repo.)
2. Change the target master branch from `Sascha-L:master` to `Sascha-L:framestep` and I'll merge it there.
3. I squash and merge this PR manually, without affecting your code, and close this PR, then.

**Pull request closed without merging**
